### ISSUE TITLE
proc to nefunguje na vsech distribucich Windows

### ISSUE THREAD

**Issue by MartinRostejnsky** [FrantisekSilhan/Encrypto#1]
nazev problemu !!!

**Comment by FrantisekSilhan** [comment]
Bohužel to není můj problém, že používáš archaickou verzi Windows jako Windows 98, která je již zastaralá a nedostává žádnou podporu. Proč bych měl trávit svůj čas řešením problémů, které jsou způsobeny tím, že se držíš zastaralých technologií? Moje rady pro tebe jsou: aktualizuj svůj operační systém a snaž se udržovat své zařízení v aktuálním stavu, abys nemusel hledat pomoc na Githubu kvůli problémům způsobeným tvým vlastním zanedbáním.
